name = "burnbadge"
main = "src/server/cf.ts"
compatibility_date = "2025-04-14"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BURNBADGE_KV"
id = "e3aad51bf51c4ab3a91aa1a25f6a5e83"

[assets]
directory = "public"
